malicious_patterns = {
    r'FileInstall, .*': 'File installation from external source',
    r'Run, "?.*\.exe"?': 'Execution of executable file',
    r'RegWrite, .*': 'Registry modification',
    r'pwhr := COM_CreateObject\("WinHttp\.WinHttpRequest\.5\.1"\)': 'HTTP request creation',
    r'RunAsAdmin\(\)': 'Attempted privilege escalation',
    r'download_file_nofreeze\(.+\)': 'File download',
    r'sonlandir\(".+"\)': 'Process termination',
    r'simge_arguman_degis\(.+, .+\)': 'Shortcut modification',
    r'DllCall\("LoadLibrary", "Str", ".+"\)': 'Dynamic library loading',
    r'Run, sc stop .*': 'Service stop command',
    r'Run, sc delete .*': 'Service deletion command',
    r'COM_GetDefaultEvents': 'Access to COM events',
    r'COM_GetGuidOfName': 'GUID retrieval from name',
    r'COM_GetTypeInfoOfGuid': 'Type information retrieval for GUID',
    r'COM_ConnectObject': 'Connection establishment to COM object',
    r'COM_ScriptControl': 'Script execution control',
    r'RegExMatch\(.*, ".*"\)': 'Regular expression usage with dynamic pattern',
    r'Scripting.Dictionary': 'Scripting.Dictionary object usage',
    r'FileOpen, .+, W': 'FileOpen with write mode',
    r'Send, .+': 'Direct keyboard input (Send command)',
    r'Critical, .+': 'Critical section for interrupt prevention',
    r'WinActivate, .+': 'Window activation',
    r'Process, .+': 'Process manipulation (Process command)',
    r'IfWinActive, .+': 'Conditional window activation',
    r'SetFormat, .+': 'SetFormat function for variable formatting',
    r'VarSetCapacity, .+': 'Memory allocation with VarSetCapacity',
    r'DetectHiddenWindows, .+': 'DetectHiddenWindows function call',
    r'ControlSend, .+': 'Sending control-specific messages (ControlSend command)',
    r'WinWaitClose, .+': 'Waiting for window closure (WinWaitClose command)',
    r'WinClose, .+': 'Force-closing a window (WinClose command)',
    r'SetEnv, .+': 'Setting environment variables (SetEnv command)',
    r'EnvGet, .+': 'Retrieving environment variables (EnvGet command)',
    r'WinGet, OutputVar, ProcessName, A': 'Retrieving process name of active window',
    r'SplitPath, OutputVar, OutNameNoExt': 'Splitting file path to get name without extension',
    r'Run Taskkill /IM %OutNameNoExt% /F': 'Forcibly terminating processes by name',
    r'Input, Key, L1 B T1 I V': 'Capturing keystrokes',
    r'browse\.navigate\("http[s]?://[^"]*"\)': 'Navigating to URL with potentially sensitive data'
}
